import { APP_PREFIX_PATH } from 'constants/route.constant'
import { NAV_ITEM_TYPE_TITLE, NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from 'constants/navigation.constant'
import { ADMIN, USER } from 'constants/roles.constant'

const appsNavigationConfig = [
  {
    key: "apps",
    path: "",
    title: "APPS",
    translateKey: "nav.apps",
    icon: "apps",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: "apps.project",
        path: "",
        title: "Project",
        translateKey: "nav.appsProject.project",
        icon: "project",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsProject.dashboard",
            path: `${APP_PREFIX_PATH}/project/dashboard`,
            title: "Dashboard",
            translateKey: "nav.appsProject.dashboard",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsProject.projectList",
            path: `${APP_PREFIX_PATH}/project/project-list`,
            title: "Project List",
            translateKey: "nav.appsProject.projectList",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsProject.scrumBoard",
            path: `${APP_PREFIX_PATH}/project/scrum-board`,
            title: "Scrum Board",
            translateKey: "nav.appsProject.scrumBoard",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsProject.issue",
            path: `${APP_PREFIX_PATH}/project/issue`,
            title: "Issue",
            translateKey: "nav.appsProject.issue",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.cloudstorage",
        path: "",
        title: "Cloud Storage",
        translateKey: "nav.appsCloudStorage.cloudstorage",
        icon: "project",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsCloudStorage.googledrive",
            path: `${APP_PREFIX_PATH}/cloudstorage/googledrive`,
            title: "Google Drive",
            translateKey: "nav.appsCloudStorage.googledrive",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsCloudStorage.onedrive",
            path: `${APP_PREFIX_PATH}/cloudstorage/onedrive`,
            title: "One Drive",
            translateKey: "nav.appsCloudStorage.onedrive",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsCloudStorage.dropbox",
            path: `${APP_PREFIX_PATH}/cloudstorage/dropbox`,
            title: "Dropbox",
            translateKey: "nav.appsCloudStorage.dropbox",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.calendar",
        path: "",
        title: "Calendar",
        translateKey: "nav.appsCalendar.calendar",
        icon: "project",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsCalendar.googlecalendar",
            path: `${APP_PREFIX_PATH}/Calendar/GoogleCalendar`,
            title: "Google Calendar",
            translateKey: "nav.appsCalendar.googlecalendar",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsCalendar.outlookcalendar",
            path: `${APP_PREFIX_PATH}/Calendar/OutlookCalendar`,
            title: "OutLook Calendar",
            translateKey: "nav.appsCalendar.outlookcalendar",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.meetings",
        path: "",
        title: "Collaborations",
        translateKey: "nav.appsmeetings.meetings",
        icon: "project",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsmeetings.teamsmeeting",
            path: `${APP_PREFIX_PATH}/teams/meetings`,
            title: "Microsoft Teams",
            translateKey: "nav.appsmeetings.teams",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsmeetings.zoommeetings",
            path: `${APP_PREFIX_PATH}/zoom/meetings`,
            title: "Zoom",
            translateKey: "nav.appsmeetings.zoommeetings",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsmeetings.slack",
            path: `${APP_PREFIX_PATH}/collaboration/slack`,
            title: "Slack",
            translateKey: "nav.appsmeetings.clickup",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsmeetings.clickup",
            path: `${APP_PREFIX_PATH}/collaboration/clickup`,
            title: "Clickup",
            translateKey: "nav.appsmeetings.clickup",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.collaboration",
        path: "",
        title: "Mails",
        translateKey: "nav.appsmails.mails",
        icon: "project",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsmails.gmail",
            path: `${APP_PREFIX_PATH}/Mails/gmail`,
            title: "Gmail",
            translateKey: "nav.appsmails.gmail",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsmails.outlookcalendar",
            path: `${APP_PREFIX_PATH}/Mails/outlookcalendar`,
            title: "OutLook Mails",
            translateKey: "nav.appsmails.outlookcalendar",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.appnotify",
        path: "",
        title: "Notifications",
        translateKey: "nav.appnotify.notification",
        icon: "project",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appnotify.sendgrid",
            path: `${APP_PREFIX_PATH}/notification/sendgrid`,
            title: "Sendgrid",
            translateKey: "nav.appnotify.gmail",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.crm",
        path: "",
        title: "Configuration",
        // translateKey: "nav.appsCrm.crm",
        icon: "crm",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsCrm.dashboard",
            path: `${APP_PREFIX_PATH}/crm/dashboard`,
            title: "Dashboard",
            translateKey: "nav.appsCrm.dashboard",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsCrm.customers",
            path: `${APP_PREFIX_PATH}/crm/customers`,
            title: "Customers",
            translateKey: "nav.appsCrm.customers",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsCrm.customerDetails",
            path: `${APP_PREFIX_PATH}/crm/customer-details?id=8`,
            title: "Customer Details",
            translateKey: "nav.appsCrm.customerDetails",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsCrm.mail",
            path: `${APP_PREFIX_PATH}/crm/mail`,
            title: "Mail",
            translateKey: "nav.appsCrm.mail",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      //   {
      //     key: "apps.sales",
      //     path: "",
      //     title: "Sales",
      //     translateKey: "nav.appsSales.sales",
      //     icon: "sales",
      //     type: NAV_ITEM_TYPE_COLLAPSE,
      //     authority: [ADMIN, USER],
      //     subMenu: [
      //       {
      //         key: "appsSales.dashboard",
      //         path: `${APP_PREFIX_PATH}/sales/dashboard`,
      //         title: "Dashboard",
      //         translateKey: "nav.appsSales.dashboard",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsSales.productList",
      //         path: `${APP_PREFIX_PATH}/sales/product-list`,
      //         title: "Product List",
      //         translateKey: "nav.appsSales.productList",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsSales.productEdit",
      //         path: `${APP_PREFIX_PATH}/sales/product-edit/12`,
      //         title: "Product Edit",
      //         translateKey: "nav.appsSales.productEdit",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsSales.productNew",
      //         path: `${APP_PREFIX_PATH}/sales/product-new`,
      //         title: "New Product",
      //         translateKey: "nav.appsSales.productNew",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsSales.orderList",
      //         path: `${APP_PREFIX_PATH}/sales/order-list`,
      //         title: "Order List",
      //         translateKey: "nav.appsSales.orderList",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsSales.orderDetails",
      //         path: `${APP_PREFIX_PATH}/sales/order-details/95954`,
      //         title: "Order Details",
      //         translateKey: "nav.appsSales.orderDetails",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //     ],
      //   },
      //   {
      //     key: "apps.crypto",
      //     path: "",
      //     title: "Crypto",
      //     translateKey: "nav.appsCrypto.crypto",
      //     icon: "crypto",
      //     type: NAV_ITEM_TYPE_COLLAPSE,
      //     authority: [ADMIN, USER],
      //     subMenu: [
      //       {
      //         key: "appsCrypto.dashboard",
      //         path: `${APP_PREFIX_PATH}/crypto/dashboard`,
      //         title: "Dashboard",
      //         translateKey: "nav.appsCrypto.dashboard",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsCrypto.portfolio",
      //         path: `${APP_PREFIX_PATH}/crypto/portfolio`,
      //         title: "Portfolio",
      //         translateKey: "nav.appsCrypto.portfolio",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsCrypto.market",
      //         path: `${APP_PREFIX_PATH}/crypto/market`,
      //         title: "Market",
      //         translateKey: "nav.appsCrypto.market",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //       {
      //         key: "appsCrypto.wallets",
      //         path: `${APP_PREFIX_PATH}/crypto/wallets`,
      //         title: "Wallets",
      //         translateKey: "nav.appsCrypto.wallets",
      //         icon: "",
      //         type: NAV_ITEM_TYPE_ITEM,
      //         authority: [ADMIN, USER],
      //         subMenu: [],
      //       },
      //     ],
      //   },
      {
        key: "apps.knowledgeBase",
        path: "",
        title: "Knowledge Base",
        translateKey: "nav.appsknowledgeBase.knowledgeBase",
        icon: "knowledgeBase",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsknowledgeBase.helpCenter",
            path: `${APP_PREFIX_PATH}/knowledge-base/help-center`,
            title: "Help Center",
            translateKey: "nav.appsknowledgeBase.helpCenter",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsknowledgeBase.article",
            path: `${APP_PREFIX_PATH}/knowledge-base/article?id=rZjCbSyae5`,
            title: "Article",
            translateKey: "nav.appsknowledgeBase.article",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsknowledgeBase.manageArticles",
            path: `${APP_PREFIX_PATH}/knowledge-base/manage-articles`,
            title: "Manage Articles",
            translateKey: "nav.appsknowledgeBase.manageArticles",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsknowledgeBase.editArticle",
            path: `${APP_PREFIX_PATH}/knowledge-base/edit-article?id=rZjCbSyae5&categoryLabel=Survey&categoryValue=survey`,
            title: "Edit Article",
            translateKey: "nav.appsknowledgeBase.editArticle",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.account",
        path: "",
        title: "Account",
        translateKey: "nav.appsAccount.account",
        icon: "account",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "appsAccount.settings",
            path: `${APP_PREFIX_PATH}/account/settings/profile`,
            title: "Settings",
            translateKey: "nav.appsAccount.settings",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "appsAccount.activityLog",
            path: `${APP_PREFIX_PATH}/account/activity-log`,
            title: "Activity Log",
            translateKey: "nav.appsAccount.activityLog",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
    ],
  },
];

export default appsNavigationConfig